name: Cycle Simulation

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  simulate:
    name: Simulation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Unit Tests
      run: dotnet test src/Engine.Tests/Engine.Tests.csproj --logger trx --results-directory "TestResults"

    - name: Run Simulation
      run: dotnet run --project src/Engine/Engine.csproj --configuration Release -- --token ${{ secrets.REPOSITORY_TOKEN }} --period-hours 24 --test-mode false

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults
      if: ${{ always() }}

    - name: Upload Characters Artifact
      uses: actions/upload-artifact@v4
      with:
        name: characters
        path: artifacts/characters.txt
